services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
        - ${ELASTIC_PATH}:/usr/share/elasticsearch/data

  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ${OLLAMA_MODELS}:/root/.ollama/
    ports:
      - "11434:11434"
    # Remove the rows below to run on CPU
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

  nicegui-app:
    image: zauberzeug/nicegui:latest
    build: .
    restart: always
    ports:
      - "80:8080"
    environment:
      - PUID=1000 # change this to your user id
      - PGID=1000 # change this to your group id
      - ${ELASTIC_URL}
    volumes:
      - ${NICEGUI_PATH}:/app/

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=PASSWORD
      - POSTGRES_USER=USERNAME
      - POSTGRES_DB=DATABASE
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data  # Use a Docker-managed named volume
    networks:
      - postgres-network

  metabase:
    volumes:
      # setup your SQLITE db (optional)
      - ./data/feedback.db:/metabase
      - ./metabase-data:/metabase-data
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=DATABASE
      - MB_DB_PORT=5432
      - MB_DB_USER=USERNAME
      - MB_DB_PASS=PASSWORD
      - MB_DB_HOST=db
    ports:
      - 3000:3000
    image: metabase/metabase
    restart: always
    depends_on:
      - db
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge

volumes:
  pgdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/pgdata  # Specify the path on the host