services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
        - /home/dmitry/.elasticsearch/data/:/usr/share/elasticsearch/data

  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - /home/dmitry/.ollama/:/root/.ollama/
    ports:
      - "11434:11434"

  nicegui-app:
    image: zauberzeug/nicegui:latest
    build: .
    restart: always
    ports:
      - "80:8080"
    environment:
      - PUID=1000 # change this to your user id
      - PGID=1000 # change this to your group id
      - ELASTIC_URL
    volumes:
      - ./:/app/

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    ports:
      - "3000:3000"  # Expose Metabase on port 3000
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db  # Store Metabase's internal database here
    volumes:
      - ./data:/metabase-data  # Map the 'data' directory to store both metabase.db and feedback.db
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5

